### ISSUE TITLE
error: 'readdir_r' is deprecated when compiling with glibc 2.24.90

### ISSUE THREAD

**Issue by dkopecek** [google/honggfuzz#82]
Hello,
 while trying to package this project for Fedora I encountered the following compilation error:
```
files.c: In function 'files_readdir':
files.c:161:9: error: 'readdir_r' is deprecated [-Werror=deprecated-declarations]
         if (readdir_r(dir, &de, &res) > 0) {
         ^~
In file included from /usr/include/features.h:397:0,
                 from /usr/include/limits.h:25,
                 from /usr/lib/gcc/x86_64-redhat-linux/6.1.1/include/limits.h:168,
                 from /usr/lib/gcc/x86_64-redhat-linux/6.1.1/include/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-redhat-linux/6.1.1/include/limits.h:34,
                 from common.h:27,
                 from files.c:24:
/usr/include/dirent.h:189:12: note: declared here
 extern int __REDIRECT (readdir_r,
```

The glibc package version used during compilation was 2.24.90.

**Comment by robertswiecki** [comment]
Thanks for the report - fixed in f2723e11fadb337b49cf718c169f7cca9adea197

**Comment by dkopecek** [comment]
There's one more place where readdir_r is used, so this is not fixed completely.
See:
https://github.com/google/honggfuzz/blob/master/linux/ptrace_utils.c#L1330

**Comment by robertswiecki** [comment]
Fixed in https://github.com/google/honggfuzz/commit/acd1cdbed3f16f2186d00b799402c7fc9736bac6
